import type { Metadata } from 'next';
import { Geist, Geist_Mono, Mulish } from 'next/font/google';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const mulish = Mulish({ variable: '--font-mulish', subsets: ['latin'] });

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${mulish.className} antialiased`}>{children}</body>
		</html>
	);
}
